// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function BatchExtract(arg1, arg2) {
  return window['go']['main']['App']['BatchExtract'](arg1, arg2);
}

export function CaptureWindowGeometry() {
  return window['go']['main']['App']['CaptureWindowGeometry']();
}

export function ExtractSingle(arg1, arg2) {
  return window['go']['main']['App']['ExtractSingle'](arg1, arg2);
}

export function GetAppInfo() {
  return window['go']['main']['App']['GetAppInfo']();
}

export function GetSavedSettings() {
  return window['go']['main']['App']['GetSavedSettings']();
}

export function LoadFile(arg1) {
  return window['go']['main']['App']['LoadFile'](arg1);
}

export function OpenFile() {
  return window['go']['main']['App']['OpenFile']();
}

export function OpenInExplorer(arg1) {
  return window['go']['main']['App']['OpenInExplorer'](arg1);
}

export function SaveTheme(arg1) {
  return window['go']['main']['App']['SaveTheme'](arg1);
}

export function SaveWindowGeometry() {
  return window['go']['main']['App']['SaveWindowGeometry']();
}
