// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {settings} from '../models';
import {peicon} from '../models';

export function BatchExtract(arg1:Array<string>,arg2:string):Promise<number>;

export function CaptureWindowGeometry():Promise<void>;

export function ExtractSingle(arg1:string,arg2:string):Promise<string>;

export function GetAppInfo():Promise<Record<string, string>>;

export function GetSavedSettings():Promise<settings.AppSettings>;

export function LoadFile(arg1:string):Promise<peicon.ParseResult>;

export function OpenFile():Promise<peicon.ParseResult>;

export function OpenInExplorer(arg1:string):Promise<void>;

export function SaveTheme(arg1:string):Promise<void>;

export function SaveWindowGeometry():Promise<void>;
